- hosts: all
  tasks:
  - name: create root ssh folder
    file: state=directory path=/root/.ssh mode=0700
  - name: copy private deploy key
    copy: src={{ private_deploy_key }} dest=/root/.ssh/id_rsa mode=0600
  - name: Update repositories cache and install "git" package
    apt:
        name: git
        update_cache: yes
  - name: inizialize repository
    command: git init
    args:
        chdir: "{{ folder_to_backup }}"
        creates: "{{ folder_to_backup }}/.git"
  - name : set remote
    command: git remote add origin {{ git_repository }}
    ignore_errors: True
    args:
        chdir: "{{ folder_to_backup }}"
  - name: copy script to cron hourly
    copy: src=./run_git_backup dest=/etc/cron.hourly/ mode=0755
  - name: trigger the first backup
    command: run-parts /etc/cron.hourly
